server:
  port: 8888

spring:
  application:
    name: metflix-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nick07242000/Parcial-Back-End-2
          searchPaths: spring-cloud-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

