server:
  port: 8086

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: final_catalogs
      port: 27017
      host: mongo-catalog

queue:
  serie:
    name: Serie
  movie:
    name: Movie

resilience4j:
  circuitbreaker:
    instances:
      catalog: #Instance name
        slidingWindowType: COUNT_BASED #Counting
        slidingWindowSize: 5 #Calls to fail
        failureRateThreshold: 50 #Fail percentage
        automaticTransitionFromOpenToHalfOpenEnabled: true #Automatic transition
        waitDurationInOpenState: 15000 #Open duration
        permittedNumberOfCallsInHalfOpenState: 3 #Calls in half-open
        registerHealthIndicator: true #Enable Resilience4j
        allowHealthIndicatorToFail: false #Status change

#Endpoint enable
management:
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Catalog Service for Back End I Final
    version: 1.0.0